### ISSUE TITLE
Withdrawing notes when inventory is full will delete your money

### ISSUE THREAD

**Issue by ninjakitty844** [Kikisito/NFCNotes#16] opened 2023-07-05 21:09 UTC
**Describe the bug**
If your inventory is full when you withdraw money, it will get deleted.

**To Reproduce**
Check your balance. Fill your inventory. Withdraw some money. Check your balance again. Your balance went down, but you do not have the notes you withdrew, effectively erasing the money.

**Expected behavior**
I would expect that either the notes should drop as items at the players feet, or the withdraw should be denied and the player is told in chat their inventory is full.

**Comment by Kikisito** [comment] 2023-07-05 23:21
Hi! I can't reproduce the issue, in my test server it denies the withdrawal correctly. Can I have your Spigot/Paper and NFCNotes versions?

**Comment by Kikisito** [comment] 2023-07-05 23:22
If any error is shown in the console, please tell me

**Comment by ninjakitty844** [comment] 2023-07-06 00:26
I am unable to reproduce it anymore, but I am 99% confident that it happened when i tried it a week ago. I forgot to file a report until now. It is possible that it was fixed when i downloaded the latest update (which I am now using, while before I was using the update 1 before that I think).

**Comment by Kikisito** [comment] 2023-07-06 09:47
If it happens again, please tell me in a new issue. Closing as it seems to be fixed.

**Closed as completed by Kikisito** 2023-07-06 09:47 UTC
Labels: invalid

**Comment by TimmyYue** [comment] 2024-01-13 03:52
I have this problem in Minecraft 1.20.2 servers
purpur-1.20.2-2091.jar

**Comment by Kikisito** [comment] 2024-01-13 11:38
> I have this problem in Minecraft 1.20.2 servers purpur-1.20.2-2091.jar

I'm unable to reproduce this issue. Please check that you are using the latest version and if the issue persists, please open a [new one](https://github.com/Kikisito/NFCNotes/issues/new/choose) with more details.
