### ISSUE TITLE
If using a placeable/usable item as note, it will be used/placed as you redeem it

### ISSUE THREAD

**Issue by ninjakitty844** [Kikisito/NFCNotes#8] opened 2023-04-09 09:53 UTC
**Describe the bug**
One example is if you use sunflower item as note (because it looks like a coin), you will place the sunflower while you redeem it. The sunflower will not drop itself as a note if you break it, luckily.

**To Reproduce**
Set material to sunflower, withdraw some money, place on ground.

**Expected behavior**
I would expect to not be able to place it, since it's money.

**Comment by kebb2-ua** [comment] 2023-04-11 10:06
Hi. I'll look into it as soon as I can! I'm busy with some university tasks, sorry for any inconvenience.

**Comment by Kikisito** [comment] 2023-04-11 10:06
Hi. I'll look into it as soon as I can! I'm busy with some university tasks, sorry for any inconvenience.

**Comment by Kikisito** [comment] 2023-04-29 23:09
This should be fixed with NFCNotes 2.3.1

https://github.com/Kikisito/NFCNotes/releases/tag/2.3.1

Please confirm if the fix works. Thanks!

**Closed as completed** 2023-04-29 23:20 UTC
Labels: bug

**Comment by ninjakitty844** [comment] 2023-04-29 23:59
I'm guessing unfortunately there isn't a way for the client to know that it can't place the block, so it does get placed for a moment on the clients screen before being undone. But it doesn't stay, so i think it is fixed.

**Comment by Kikisito** [comment] 2023-04-30 00:28
As you said, there is no way to make the client know that. The only
scenario the client knows it can't place blocks is in adventure mode and
this is not a solution for this issue.

The fix I used for the issue is the same method that uses, for example,
WorldGuard to prevent players to place blocks in areas where they are not
allowed to.

I'm sorry but this is a Minecraft limitation. Anyways, I hope the fix is
useful.
